package arch

import (
	"encoding/hex"
	"testing"

	"github.com/btcsuite/btcd/btcec/v2/schnorr"
)

func TestSignerPubkey(t *testing.T) {
	// Same secret seed (0x11 repeated 32 times) used by sub-projects 1 and 2.
	secretHex := "1111111111111111111111111111111111111111111111111111111111111111"
	s, err := NewSignerFromHex(secretHex)
	if err != nil {
		t.Fatalf("NewSignerFromHex: %v", err)
	}
	pk := s.Pubkey()
	// The x-only pubkey for seed 0x11 — generated by sub-project 2's keypair.test.ts using @noble/curves.
	// Regenerated via: node -e 'const {secp256k1}=require("@noble/curves/secp256k1"); console.log(Buffer.from(secp256k1.getPublicKey(new Uint8Array(32).fill(0x11),true).slice(1)).toString("hex"))'
	want := "4f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa"
	got := hex.EncodeToString(pk[:])
	if got != want {
		t.Fatalf("pubkey mismatch: got %s want %s", got, want)
	}
}

func TestSignerSignAndVerify(t *testing.T) {
	secretHex := "1111111111111111111111111111111111111111111111111111111111111111"
	s, err := NewSignerFromHex(secretHex)
	if err != nil {
		t.Fatalf("NewSignerFromHex: %v", err)
	}
	var digest [32]byte
	copy(digest[:], []byte("test-digest-padded-to-32-bytes!!"))
	sig, err := s.SignDigest(digest)
	if err != nil {
		t.Fatalf("SignDigest: %v", err)
	}
	// Verify with the schnorr library directly to confirm Schnorr signature conformance.
	// The test is in the same package, so we can access s.secret directly to obtain
	// the full public key (including y-parity) for verification.
	pub := s.secret.PubKey()
	parsed, err := schnorr.ParseSignature(sig[:])
	if err != nil {
		t.Fatalf("parse signature: %v", err)
	}
	if !parsed.Verify(digest[:], pub) {
		t.Fatalf("Schnorr verification failed")
	}
}
