// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Oracle intent data structure
type OracleIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentType    string                 `protobuf:"bytes,1,opt,name=intent_type,json=intentType,proto3" json:"intent_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ChainId       string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // Using string for big.Int
	Nonce         string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                    // Using string for big.Int
	Expiry        string                 `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`                  // Using string for big.Int
	Symbol        string                 `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`         // Using string for big.Int
	Timestamp     string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Using string for big.Int
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	Signature     []byte                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	Signer        string                 `protobuf:"bytes,11,opt,name=signer,proto3" json:"signer,omitempty"` // Ethereum address as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OracleIntent) Reset() {
	*x = OracleIntent{}
	mi := &file_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleIntent) ProtoMessage() {}

func (x *OracleIntent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleIntent.ProtoReflect.Descriptor instead.
func (*OracleIntent) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *OracleIntent) GetIntentType() string {
	if x != nil {
		return x.IntentType
	}
	return ""
}

func (x *OracleIntent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OracleIntent) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *OracleIntent) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *OracleIntent) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *OracleIntent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OracleIntent) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OracleIntent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OracleIntent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OracleIntent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *OracleIntent) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

// Request to trigger a failover
type FailoverRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MessageId                string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IntentHash               string                 `protobuf:"bytes,2,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	PairId                   string                 `protobuf:"bytes,3,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	SourceChainId            int64                  `protobuf:"varint,4,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	DestinationChainId       int64                  `protobuf:"varint,5,opt,name=destination_chain_id,json=destinationChainId,proto3" json:"destination_chain_id,omitempty"`
	ReceiverAddress          string                 `protobuf:"bytes,6,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	IntentData               *OracleIntent          `protobuf:"bytes,7,opt,name=intent_data,json=intentData,proto3" json:"intent_data,omitempty"`
	Reason                   string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	DetectionTimestamp       int64                  `protobuf:"varint,9,opt,name=detection_timestamp,json=detectionTimestamp,proto3" json:"detection_timestamp,omitempty"`
	MonitoringStartTimestamp int64                  `protobuf:"varint,10,opt,name=monitoring_start_timestamp,json=monitoringStartTimestamp,proto3" json:"monitoring_start_timestamp,omitempty"`
	FailoverTimestamp        int64                  `protobuf:"varint,11,opt,name=failover_timestamp,json=failoverTimestamp,proto3" json:"failover_timestamp,omitempty"`
	ReceiverKey              string                 `protobuf:"bytes,12,opt,name=receiver_key,json=receiverKey,proto3" json:"receiver_key,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *FailoverRequest) Reset() {
	*x = FailoverRequest{}
	mi := &file_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailoverRequest) ProtoMessage() {}

func (x *FailoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailoverRequest.ProtoReflect.Descriptor instead.
func (*FailoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *FailoverRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *FailoverRequest) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *FailoverRequest) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

func (x *FailoverRequest) GetSourceChainId() int64 {
	if x != nil {
		return x.SourceChainId
	}
	return 0
}

func (x *FailoverRequest) GetDestinationChainId() int64 {
	if x != nil {
		return x.DestinationChainId
	}
	return 0
}

func (x *FailoverRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *FailoverRequest) GetIntentData() *OracleIntent {
	if x != nil {
		return x.IntentData
	}
	return nil
}

func (x *FailoverRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FailoverRequest) GetDetectionTimestamp() int64 {
	if x != nil {
		return x.DetectionTimestamp
	}
	return 0
}

func (x *FailoverRequest) GetMonitoringStartTimestamp() int64 {
	if x != nil {
		return x.MonitoringStartTimestamp
	}
	return 0
}

func (x *FailoverRequest) GetFailoverTimestamp() int64 {
	if x != nil {
		return x.FailoverTimestamp
	}
	return 0
}

func (x *FailoverRequest) GetReceiverKey() string {
	if x != nil {
		return x.ReceiverKey
	}
	return ""
}

// Response from failover trigger
type FailoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailoverResponse) Reset() {
	*x = FailoverResponse{}
	mi := &file_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailoverResponse) ProtoMessage() {}

func (x *FailoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailoverResponse.ProtoReflect.Descriptor instead.
func (*FailoverResponse) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *FailoverResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FailoverResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FailoverResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FailoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to check failover status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Response with failover status
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *StatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{5}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Healthy       bool                    `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                   `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ChainStatus   map[string]*ChainStatus `protobuf:"bytes,4,rep,name=chain_status,json=chainStatus,proto3" json:"chain_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetChainStatus() map[string]*ChainStatus {
	if x != nil {
		return x.ChainStatus
	}
	return nil
}

// Chain connection status
type ChainStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	LastBlock     int64                  `protobuf:"varint,2,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStatus) Reset() {
	*x = ChainStatus{}
	mi := &file_proto_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStatus) ProtoMessage() {}

func (x *ChainStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStatus.ProtoReflect.Descriptor instead.
func (*ChainStatus) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *ChainStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ChainStatus) GetLastBlock() int64 {
	if x != nil {
		return x.LastBlock
	}
	return 0
}

func (x *ChainStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_bridge_proto protoreflect.FileDescriptor

const file_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"\x12proto/bridge.proto\x12\x06bridge\"\xac\x02\n" +
	"\fOracleIntent\x12\x1f\n" +
	"\vintent_type\x18\x01 \x01(\tR\n" +
	"intentType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\tR\x06expiry\x12\x16\n" +
	"\x06symbol\x18\x06 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x12\x16\n" +
	"\x06signer\x18\v \x01(\tR\x06signer\"\xff\x03\n" +
	"\x0fFailoverRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vintent_hash\x18\x02 \x01(\tR\n" +
	"intentHash\x12\x17\n" +
	"\apair_id\x18\x03 \x01(\tR\x06pairId\x12&\n" +
	"\x0fsource_chain_id\x18\x04 \x01(\x03R\rsourceChainId\x120\n" +
	"\x14destination_chain_id\x18\x05 \x01(\x03R\x12destinationChainId\x12)\n" +
	"\x10receiver_address\x18\x06 \x01(\tR\x0freceiverAddress\x125\n" +
	"\vintent_data\x18\a \x01(\v2\x14.bridge.OracleIntentR\n" +
	"intentData\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12/\n" +
	"\x13detection_timestamp\x18\t \x01(\x03R\x12detectionTimestamp\x12<\n" +
	"\x1amonitoring_start_timestamp\x18\n" +
	" \x01(\x03R\x18monitoringStartTimestamp\x12-\n" +
	"\x12failover_timestamp\x18\v \x01(\x03R\x11failoverTimestamp\x12!\n" +
	"\freceiver_key\x18\f \x01(\tR\vreceiverKey\"\x81\x01\n" +
	"\x10FailoverResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xc3\x01\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x0f\n" +
	"\rHealthRequest\"\x8c\x02\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12J\n" +
	"\fchain_status\x18\x04 \x03(\v2'.bridge.HealthResponse.ChainStatusEntryR\vchainStatus\x1aS\n" +
	"\x10ChainStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.bridge.ChainStatusR\x05value:\x028\x01\"`\n" +
	"\vChainStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1d\n" +
	"\n" +
	"last_block\x18\x02 \x01(\x03R\tlastBlock\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xd7\x01\n" +
	"\rBridgeService\x12D\n" +
	"\x0fTriggerFailover\x12\x17.bridge.FailoverRequest\x1a\x18.bridge.FailoverResponse\x12B\n" +
	"\x11GetFailoverStatus\x12\x15.bridge.StatusRequest\x1a\x16.bridge.StatusResponse\x12<\n" +
	"\vHealthCheck\x12\x15.bridge.HealthRequest\x1a\x16.bridge.HealthResponseB>Z<github.com/diadata.org/Spectra-interoperability/services/bridge/protob\x06proto3"

var (
	file_proto_bridge_proto_rawDescOnce sync.Once
	file_proto_bridge_proto_rawDescData []byte
)

func file_proto_bridge_proto_rawDescGZIP() []byte {
	file_proto_bridge_proto_rawDescOnce.Do(func() {
		file_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)))
	})
	return file_proto_bridge_proto_rawDescData
}

var file_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_bridge_proto_goTypes = []any{
	(*OracleIntent)(nil),     // 0: bridge.OracleIntent
	(*FailoverRequest)(nil),  // 1: bridge.FailoverRequest
	(*FailoverResponse)(nil), // 2: bridge.FailoverResponse
	(*StatusRequest)(nil),    // 3: bridge.StatusRequest
	(*StatusResponse)(nil),   // 4: bridge.StatusResponse
	(*HealthRequest)(nil),    // 5: bridge.HealthRequest
	(*HealthResponse)(nil),   // 6: bridge.HealthResponse
	(*ChainStatus)(nil),      // 7: bridge.ChainStatus
	nil,                      // 8: bridge.HealthResponse.ChainStatusEntry
}
var file_proto_bridge_proto_depIdxs = []int32{
	0, // 0: bridge.FailoverRequest.intent_data:type_name -> bridge.OracleIntent
	8, // 1: bridge.HealthResponse.chain_status:type_name -> bridge.HealthResponse.ChainStatusEntry
	7, // 2: bridge.HealthResponse.ChainStatusEntry.value:type_name -> bridge.ChainStatus
	1, // 3: bridge.BridgeService.TriggerFailover:input_type -> bridge.FailoverRequest
	3, // 4: bridge.BridgeService.GetFailoverStatus:input_type -> bridge.StatusRequest
	5, // 5: bridge.BridgeService.HealthCheck:input_type -> bridge.HealthRequest
	2, // 6: bridge.BridgeService.TriggerFailover:output_type -> bridge.FailoverResponse
	4, // 7: bridge.BridgeService.GetFailoverStatus:output_type -> bridge.StatusResponse
	6, // 8: bridge.BridgeService.HealthCheck:output_type -> bridge.HealthResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_bridge_proto_init() }
func file_proto_bridge_proto_init() {
	if File_proto_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bridge_proto_goTypes,
		DependencyIndexes: file_proto_bridge_proto_depIdxs,
		MessageInfos:      file_proto_bridge_proto_msgTypes,
	}.Build()
	File_proto_bridge_proto = out.File
	file_proto_bridge_proto_goTypes = nil
	file_proto_bridge_proto_depIdxs = nil
}
